/*
  # Finding a customer by the number that is calling

  A phone number is written six different ways — `+962 77 806 8705`,
  `0778068705`, `77806 8705` — and the customer list only ever did a substring
  match on whatever happened to be typed, so the same person did not match
  themselves.

  Each customer now carries a derived key: the number stripped of everything
  that varies. Non-digits go, then the country code (`00962` or `962`), then any
  leading zero, and what is left is capped at nine digits. That makes
  `+962 77 806 8705`, `0778068705` and `77806 8705` the same key — and, just as
  importantly, `+962 6 551 2345` and `06 551 2345`, which a last-nine-digits
  rule alone would have got wrong for every landline.

  The key is generated by the database, so it can never drift from the number it
  came from, and it is indexed so a lookup at the moment the phone rings is a
  single index hit.

  Corporate records get the same treatment for their contact person, because
  that is who actually calls.
*/

ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS phone_key text
    GENERATED ALWAYS AS (
      right(
        regexp_replace(
          regexp_replace(regexp_replace(COALESCE(phone, ''), '\D', '', 'g'), '^(00)?962', ''),
          '^0+', ''),
        9)
    ) STORED;

ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS contact_phone_key text
    GENERATED ALWAYS AS (
      right(
        regexp_replace(
          regexp_replace(regexp_replace(COALESCE(contact_person_phone, ''), '\D', '', 'g'), '^(00)?962', ''),
          '^0+', ''),
        9)
    ) STORED;

CREATE INDEX IF NOT EXISTS customers_phone_key_idx
  ON customers (phone_key) WHERE phone_key <> '';

CREATE INDEX IF NOT EXISTS customers_contact_phone_key_idx
  ON customers (contact_phone_key) WHERE contact_phone_key <> '';
